# Generated by Django 2.1.14 on 2019-11-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredint',
            new_name='ingredints',
        ),
    ]
